### ISSUE TITLE
Plugin needs to connect to the dimensionNamesChanged event to catch when the user changes a feature name

### ISSUE THREAD

**Issue by JulianThijssen** [ManiVaultStudio/PcaPlugin#10]

**Comment by alxvth** [comment]
Maybe this should be solved in the `DimensionsPickerAction`, see https://github.com/ManiVaultStudio/core/pull/487 ?

**Comment by alxvth** [comment]
Solved with https://github.com/ManiVaultStudio/core/pull/487
