### ISSUE TITLE
HSNE after PCA loses correspondence between landmarks and data

### ISSUE THREAD

**Issue by bleliev** [ManiVaultStudio/PcaPlugin#4]
I've  find a quirk with the PCA plugin: If you load the MNIST, and do a PCA with 50 components (using the COV option), and then: 
-Do a tSNE on the PC's
-Do an HSNE on the PC's

It loses the correpondence between the lanmarks and the datapoints. 

This does't happen when applying tSNE and HSNE direcly on the source data, but only after pre-processing with PCA, so it seems to be localized in the PCA plugin, where some mapping function in the HSNE is quirking...

**Comment by alxvth** [comment]
This is solved thanks to a recent fix in the core, @bleliev:

Left: PCA, Center: HSNE (on 50 PCs) and drill down, right: t-SNE (on 50 PCs)
![image](https://github.com/ManiVaultStudio/PcaPlugin/assets/58806453/eefac080-22cb-4ba8-8f53-26ed1678f191)
